import { TrendingTopic, NewsItem, Job, AcademicMaterial, CampusEvent, FeaturedNews } from '../../types';

export const mockFeaturedNews: FeaturedNews = {
  id: 'featured-1',
  title: 'Curfew Imposed On Student Amid UNIBEN Shooting',
  description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud en',
  image: 'https://images.unsplash.com/photo-1562774053-701939374585?w=800',
  timeAgo: '1h ago',
  category: 'Announcement',
  isBookmarked: false,
};

export const mockTrendingTopics: TrendingTopic[] = [
  { id: 'trend-1', rank: 1, hashtag: '#SUGElections', postsCount: 1240, isHot: true },
  { id: 'trend-2', rank: 2, hashtag: '#Hakathon', postsCount: 840, isHot: true },
  { id: 'trend-3', rank: 3, hashtag: '#ExamSeason', postsCount: 3040 },
  { id: 'trend-4', rank: 4, hashtag: '#MainGate', postsCount: 5400 },
  { id: 'trend-5', rank: 5, hashtag: '#UniZikSUG', postsCount: 321 },
  { id: 'trend-6', rank: 6, hashtag: '#OZOROfestival', postsCount: 10000 },
  { id: 'trend-7', rank: 7, hashtag: '#Prof. Adeyemi', postsCount: 850 },
  { id: 'trend-8', rank: 8, hashtag: '#ASUU', postsCount: 6700 },
  { id: 'trend-9', rank: 9, hashtag: '#NewSession', postsCount: 4200 },
  { id: 'trend-10', rank: 10, hashtag: '#CampusVibes', postsCount: 2100 },
];

export const mockNewsItems: NewsItem[] = [
  { id: 'news-1', date: '07/07 (Wed)', dayOfWeek: 'Wed', title: 'SUG Student to return to school on', isNew: true },
  { id: 'news-2', date: '07/07 (Wed)', dayOfWeek: 'Wed', title: '(RECAPS) Seminars in July', isNew: true },
  { id: 'news-3', date: '07/06 (Tue)', dayOfWeek: 'Tue', title: 'SAS "Summer with SAS" Event info.....', isNew: false },
  { id: 'news-4', date: '07/06 (Tue)', dayOfWeek: 'Tue', title: 'Questionnaire Use your voice to make APU even a better place', isNew: false },
  { id: 'news-5', date: '07/06 (Tue)', dayOfWeek: 'Tue', title: 'VISA Insurance of recommendation letter and applying for a VISA to stay in Japan for........', isNew: false },
  { id: 'news-6', date: '07/06 (Tue)', dayOfWeek: 'Tue', title: '(Writing center) Advanced writing workshop', isNew: false },
  { id: 'news-7', date: '07/06 (Tue)', dayOfWeek: 'Tue', title: "Recruit Wanted! International students needed to support high school students", isNew: false },
  { id: 'news-8', date: '07/06 (Tue)', dayOfWeek: 'Tue', title: 'SALC Online Lounge on July 15 (6th period) |', isNew: false },
  { id: 'news-9', date: '07/05 (Mon)', dayOfWeek: 'Mon', title: '(Career office) Career consultation by PASONA Group, DISCO Inc. and Tokyo campus', isNew: false },
  { id: 'news-10', date: '07/05 (Mon)', dayOfWeek: 'Mon', title: '(Recruitment) AMC Tutir recruitment - Use your maths skills and support other students', isNew: false },
  { id: 'news-11', date: '07/04 (Sun)', dayOfWeek: 'Sun', title: 'Library extended hours announced for exam period', isNew: false },
  { id: 'news-12', date: '07/04 (Sun)', dayOfWeek: 'Sun', title: 'New student portal launch date confirmed', isNew: false },
  { id: 'news-13', date: '07/03 (Sat)', dayOfWeek: 'Sat', title: 'Inter-university debate competition registration open', isNew: false },
  { id: 'news-14', date: '07/03 (Sat)', dayOfWeek: 'Sat', title: 'Campus shuttle route update effective next week', isNew: false },
  { id: 'news-15', date: '07/02 (Fri)', dayOfWeek: 'Fri', title: 'Student health insurance enrollment deadline reminder', isNew: false },
];

export const mockJobs: Job[] = [
  {
    id: 'job-1',
    title: 'Workflow Automation Intern',
    company: 'TechCorp Nigeria',
    category: 'Tech',
    description: "We're offering a chance to learn, contribute, and grow professionally.",
    image: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=600',
    isBookmarked: false,
    type: 'job',
  },
  {
    id: 'job-2',
    title: 'Workflow Automation Intern',
    company: 'DataFlow Inc',
    category: 'Tech',
    description: "We're offering a chance to learn, contribute, and grow professionally.",
    image: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=600',
    isBookmarked: false,
    type: 'job',
  },
  {
    id: 'job-3',
    title: 'Marketing Associate',
    company: 'BrandHub Africa',
    category: 'Marketing',
    description: 'Join our marketing team to help build brand awareness across campuses.',
    image: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=600',
    isBookmarked: false,
    type: 'job',
  },
  {
    id: 'job-4',
    title: 'Content Writer',
    company: 'EduMedia',
    category: 'Writing',
    description: 'Create engaging content for our educational platform.',
    image: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?w=600',
    isBookmarked: false,
    type: 'job',
  },
  {
    id: 'job-5',
    title: 'Study Abroad in Canada',
    company: 'Global Education Partners',
    category: 'Education',
    description: 'Start your academic journey with access to top universities and global opportunities.',
    image: 'https://images.unsplash.com/photo-1503614472-8c93d56e92ce?w=600',
    isBookmarked: false,
    type: 'abroad',
  },
  {
    id: 'job-6',
    title: 'Global Learning Opportunities',
    company: 'WorldLearn',
    category: 'Education',
    description: 'Access international programs designed for success anywhere.',
    image: 'https://images.unsplash.com/photo-1436491865332-7a61a109db05?w=600',
    isBookmarked: false,
    type: 'abroad',
  },
  {
    id: 'job-7',
    title: 'Research Assistant',
    company: 'UniResearch Labs',
    category: 'Research',
    description: 'Assist professors with cutting-edge research projects.',
    image: 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?w=600',
    isBookmarked: false,
    type: 'job',
  },
  {
    id: 'job-8',
    title: 'UI/UX Design Intern',
    company: 'DesignLab NG',
    category: 'Design',
    description: 'Design beautiful interfaces for mobile and web applications.',
    image: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=600',
    isBookmarked: false,
    type: 'job',
  },
  {
    id: 'job-9',
    title: 'Campus Ambassador',
    company: 'StartupHub',
    category: 'Marketing',
    description: 'Represent our brand on campus and organize events.',
    image: 'https://images.unsplash.com/photo-1523580494863-6f3031224c94?w=600',
    isBookmarked: false,
    type: 'job',
  },
  {
    id: 'job-10',
    title: 'Data Analyst Intern',
    company: 'AnalyticsPro',
    category: 'Tech',
    description: 'Analyze data to drive business decisions.',
    image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=600',
    isBookmarked: false,
    type: 'job',
  },
];

export const mockAcademicMaterials: AcademicMaterial[] = [
  {
    id: 'acad-1',
    courseCode: 'CHEM 101',
    title: 'Introduction To Chem',
    author: { name: 'Jane Cooper', avatar: 'https://i.pravatar.cc/150?img=5' },
    image: 'https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=600',
    university: 'University of Benin',
  },
  {
    id: 'acad-2',
    courseCode: 'CSC 121',
    title: 'How To Code with AI',
    author: { name: 'Peter Ifediora', avatar: 'https://i.pravatar.cc/150?img=53' },
    image: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=600',
    university: 'University of Nigeria',
  },
  {
    id: 'acad-3',
    courseCode: 'ACH 101',
    title: 'Building Bridges',
    author: { name: 'Jane Abiodun', avatar: 'https://i.pravatar.cc/150?img=44' },
    image: 'https://images.unsplash.com/photo-1486325212027-8081e485255e?w=600',
    university: 'University of Benin',
  },
  {
    id: 'acad-4',
    courseCode: 'PHY 201',
    title: 'Quantum Mechanics Basics',
    author: { name: 'Ngozi Okafor', avatar: 'https://i.pravatar.cc/150?img=47' },
    image: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=600',
    university: 'University of Jos',
  },
  {
    id: 'acad-5',
    courseCode: 'ENG 301',
    title: 'Advanced Circuit Design',
    author: { name: 'Emeka Okoro', avatar: 'https://i.pravatar.cc/150?img=52' },
    image: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=600',
    university: 'University of Ilorin',
  },
  {
    id: 'acad-6',
    courseCode: 'BIO 101',
    title: 'Cell Biology Fundamentals',
    author: { name: 'Aisha Mohammed', avatar: 'https://i.pravatar.cc/150?img=45' },
    image: 'https://images.unsplash.com/photo-1576086213369-97a306d36557?w=600',
    university: 'University of Ilorin',
  },
  {
    id: 'acad-7',
    courseCode: 'MTH 201',
    title: 'Linear Algebra Made Easy',
    author: { name: 'Femi Ogundimu', avatar: 'https://i.pravatar.cc/150?img=14' },
    image: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=600',
    university: 'University of Ibadan',
  },
  {
    id: 'acad-8',
    courseCode: 'LAW 101',
    title: 'Introduction to Nigerian Law',
    author: { name: 'Adaeze Eze', avatar: 'https://i.pravatar.cc/150?img=38' },
    image: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=600',
    university: 'University of Calabar',
  },
  {
    id: 'acad-9',
    courseCode: 'ECO 101',
    title: 'Microeconomics Principles',
    author: { name: 'Femi Ogundimu', avatar: 'https://i.pravatar.cc/150?img=14' },
    image: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=600',
    university: 'University of Ibadan',
  },
  {
    id: 'acad-10',
    courseCode: 'MED 301',
    title: 'Clinical Anatomy Review',
    author: { name: 'Chukwudi Eze', avatar: 'https://i.pravatar.cc/150?img=57' },
    image: 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=600',
    university: 'University of Nigeria',
  },
  {
    id: 'acad-11',
    courseCode: 'AGR 201',
    title: 'Soil Science Essentials',
    author: { name: 'Chidera Nwosu', avatar: 'https://i.pravatar.cc/150?img=51' },
    image: 'https://images.unsplash.com/photo-1574943320219-553eb213f72d?w=600',
    university: 'Obafemi Awolowo University',
  },
  {
    id: 'acad-12',
    courseCode: 'CSC 301',
    title: 'Data Structures & Algorithms',
    author: { name: 'Oluwaseun Bello', avatar: 'https://i.pravatar.cc/150?img=56' },
    image: 'https://images.unsplash.com/photo-1555949963-ff9fe0c870eb?w=600',
    university: 'Covenant University',
  },
  {
    id: 'acad-13',
    courseCode: 'NUR 201',
    title: 'Patient Care Techniques',
    author: { name: 'Grace Udo', avatar: 'https://i.pravatar.cc/150?img=41' },
    image: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=600',
    university: 'University of Uyo',
  },
  {
    id: 'acad-14',
    courseCode: 'POL 301',
    title: 'International Relations',
    author: { name: 'Ibrahim Musa', avatar: 'https://i.pravatar.cc/150?img=59' },
    image: 'https://images.unsplash.com/photo-1529107386315-e1a2ed48a620?w=600',
    university: 'Bayero University',
  },
  {
    id: 'acad-15',
    courseCode: 'MCE 401',
    title: 'Robotics Engineering',
    author: { name: 'Samuel Adeyemi', avatar: 'https://i.pravatar.cc/150?img=60' },
    image: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=600',
    university: 'Federal University of Technology, Akure',
  },
];

export const mockEvents: CampusEvent[] = [
  {
    id: 'event-1',
    title: 'Tech Innovation Summit 2025',
    description: 'Annual technology conference featuring student startups.',
    date: '2025-07-15',
    time: '10:00 AM',
    location: 'Main Auditorium, UNILAG',
    image: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=600',
    university: 'University of Lagos',
    isBookmarked: false,
  },
  {
    id: 'event-2',
    title: 'Inter-Faculty Sports Day',
    description: 'Annual sports competition between all faculties.',
    date: '2025-07-20',
    time: '8:00 AM',
    location: 'Sports Complex, UNIBEN',
    image: 'https://images.unsplash.com/photo-1461896836934-bd45ba8fcb1f?w=600',
    university: 'University of Benin',
    isBookmarked: false,
  },
  {
    id: 'event-3',
    title: 'Career Fair 2025',
    description: 'Meet top employers and explore career opportunities.',
    date: '2025-07-25',
    time: '9:00 AM',
    location: 'Exhibition Hall, ABU',
    image: 'https://images.unsplash.com/photo-1523580494863-6f3031224c94?w=600',
    university: 'Ahmadu Bello University',
    isBookmarked: false,
  },
  {
    id: 'event-4',
    title: 'Coding Bootcamp',
    description: 'Free 3-day coding bootcamp for beginners.',
    date: '2025-08-01',
    time: '2:00 PM',
    location: 'CS Department, UNN',
    image: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=600',
    university: 'University of Nigeria',
    isBookmarked: false,
  },
  {
    id: 'event-5',
    title: 'Art Exhibition: Campus Life',
    description: 'Student artwork celebrating campus culture.',
    date: '2025-08-05',
    time: '11:00 AM',
    location: 'Gallery Space, UI',
    image: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=600',
    university: 'University of Ibadan',
    isBookmarked: false,
  },
  {
    id: 'event-6',
    title: 'Debate Championship Finals',
    description: 'Watch the best debaters compete for the trophy.',
    date: '2025-08-10',
    time: '4:00 PM',
    location: 'Senate Building, OAU',
    image: 'https://images.unsplash.com/photo-1475721027785-f74eccf877e2?w=600',
    university: 'Obafemi Awolowo University',
    isBookmarked: false,
  },
  {
    id: 'event-7',
    title: 'Freshers Welcome Party',
    description: 'Welcome new students to campus life.',
    date: '2025-09-01',
    time: '6:00 PM',
    location: 'Quad, UNIPORT',
    image: 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=600',
    university: 'University of Port Harcourt',
    isBookmarked: false,
  },
  {
    id: 'event-8',
    title: 'Science Fair',
    description: 'Showcase student research projects and innovations.',
    date: '2025-08-15',
    time: '10:00 AM',
    location: 'Science Complex, FUTA',
    image: 'https://images.unsplash.com/photo-1507413245164-6160d8298b31?w=600',
    university: 'Federal University of Technology, Akure',
    isBookmarked: false,
  },
  {
    id: 'event-9',
    title: 'Cultural Day Festival',
    description: 'Celebrating Nigerian cultural diversity on campus.',
    date: '2025-08-20',
    time: '12:00 PM',
    location: 'Open Field, BUK',
    image: 'https://images.unsplash.com/photo-1511632765486-a01980e01a18?w=600',
    university: 'Bayero University',
    isBookmarked: false,
  },
  {
    id: 'event-10',
    title: 'Entrepreneurship Workshop',
    description: 'Learn how to build and pitch your startup.',
    date: '2025-08-25',
    time: '1:00 PM',
    location: 'Business School, CU',
    image: 'https://images.unsplash.com/photo-1559136555-9303baea8ebd?w=600',
    university: 'Covenant University',
    isBookmarked: false,
  },
  {
    id: 'event-11',
    title: 'Medical Outreach',
    description: 'Free health checks for surrounding communities.',
    date: '2025-09-05',
    time: '9:00 AM',
    location: 'Health Center, UNIUYO',
    image: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=600',
    university: 'University of Uyo',
    isBookmarked: false,
  },
  {
    id: 'event-12',
    title: 'Stargazing Night',
    description: 'Telescopic viewing and astronomy lectures.',
    date: '2025-07-28',
    time: '8:00 PM',
    location: 'Rooftop, UNIJOS',
    image: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?w=600',
    university: 'University of Jos',
    isBookmarked: false,
  },
  {
    id: 'event-13',
    title: 'Environmental Summit',
    description: 'Discussing sustainability on campus.',
    date: '2025-08-08',
    time: '10:00 AM',
    location: 'Conference Hall, UNICAL',
    image: 'https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?w=600',
    university: 'University of Calabar',
    isBookmarked: false,
  },
  {
    id: 'event-14',
    title: 'Alumni Networking Night',
    description: 'Connect with successful graduates.',
    date: '2025-09-10',
    time: '5:00 PM',
    location: 'Alumni House, UNILORIN',
    image: 'https://images.unsplash.com/photo-1515187029135-18ee286d815b?w=600',
    university: 'University of Ilorin',
    isBookmarked: false,
  },
  {
    id: 'event-15',
    title: 'Hackathon 2025',
    description: '48-hour coding competition with prizes.',
    date: '2025-09-15',
    time: '12:00 PM',
    location: 'Innovation Hub, UNIABUJA',
    image: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=600',
    university: 'University of Abuja',
    isBookmarked: false,
  },
];
