import { Notification } from '../types';

export const mockNotifications: Notification[] = [
  {
    id: 'notif-1',
    title: 'Curfew Restriction for Uinben student admist Shooting',
    timeAgo: 'Now',
    isRead: false,
    type: 'announcement',
  },
  {
    id: 'notif-2',
    title: 'Jamb cutoff mark reduced to 180 for major courses (medicine, nursing, e.t.c)',
    timeAgo: '2h ago',
    isRead: false,
    type: 'academic',
  },
  {
    id: 'notif-3',
    title: 'Uniport Students reacts to the Strike after the sixth time this year',
    timeAgo: '6h ago',
    isRead: true,
    type: 'announcement',
  },
  {
    id: 'notif-4',
    title: 'Your student-teaching is coming on the 2nd of April. Be prepared!',
    timeAgo: '1d',
    isRead: true,
    type: 'academic',
  },
  {
    id: 'notif-5',
    title: "Students are advised to make sure their phones aren't on DND as insecurity surges- Vice Chancellor",
    timeAgo: '2w',
    isRead: true,
    type: 'announcement',
  },
  {
    id: 'notif-6',
    title: 'Uniben welcome the new student of 2025/2026 session as marticulation event as dignitaries attend',
    timeAgo: '3w',
    isRead: true,
    type: 'social',
  },
  {
    id: 'notif-7',
    title: 'New scholarship applications now open for engineering students',
    timeAgo: '3w',
    isRead: true,
    type: 'academic',
  },
  {
    id: 'notif-8',
    title: 'Campus security upgrade: New ID card verification system active',
    timeAgo: '1mo',
    isRead: true,
    type: 'general',
  },
  {
    id: 'notif-9',
    title: 'Library hours extended during exam period — now open until midnight',
    timeAgo: '1mo',
    isRead: true,
    type: 'general',
  },
  {
    id: 'notif-10',
    title: 'Inter-faculty sports competition registration deadline tomorrow',
    timeAgo: '1mo',
    isRead: true,
    type: 'social',
  },
  {
    id: 'notif-11',
    title: 'Course registration portal closes this Friday at 11:59 PM',
    timeAgo: '1mo',
    isRead: true,
    type: 'academic',
  },
  {
    id: 'notif-12',
    title: 'Free coding workshop by Google Developer Student Club next week',
    timeAgo: '2mo',
    isRead: true,
    type: 'social',
  },
  {
    id: 'notif-13',
    title: 'Hostel allocation results have been posted on the student portal',
    timeAgo: '2mo',
    isRead: true,
    type: 'general',
  },
  {
    id: 'notif-14',
    title: 'New campus bus schedule effective from Monday',
    timeAgo: '2mo',
    isRead: true,
    type: 'general',
  },
  {
    id: 'notif-15',
    title: 'Career fair featuring top Nigerian employers next month',
    timeAgo: '3mo',
    isRead: true,
    type: 'social',
  },
];
