import { User, University } from '../../types';

export const mockUniversities: Record<string, University> = {
  uniben: { id: 'uni-1', name: 'University of Benin', shortName: 'UNIBEN', location: 'Benin City, Edo State' },
  unilag: { id: 'uni-2', name: 'University of Lagos', shortName: 'UNILAG', location: 'Lagos, Lagos State' },
  abu: { id: 'uni-3', name: 'Ahmadu Bello University', shortName: 'ABU', location: 'Zaria, Kaduna State' },
  ui: { id: 'uni-4', name: 'University of Ibadan', shortName: 'UI', location: 'Ibadan, Oyo State' },
  oau: { id: 'uni-5', name: 'Obafemi Awolowo University', shortName: 'OAU', location: 'Ile-Ife, Osun State' },
  unn: { id: 'uni-6', name: 'University of Nigeria', shortName: 'UNN', location: 'Nsukka, Enugu State' },
  uniport: { id: 'uni-7', name: 'University of Port Harcourt', shortName: 'UNIPORT', location: 'Port Harcourt, Rivers State' },
  uniabuja: { id: 'uni-8', name: 'University of Abuja', shortName: 'UNIABUJA', location: 'Abuja, FCT' },
  unilorin: { id: 'uni-9', name: 'University of Ilorin', shortName: 'UNILORIN', location: 'Ilorin, Kwara State' },
  unical: { id: 'uni-10', name: 'University of Calabar', shortName: 'UNICAL', location: 'Calabar, Cross River State' },
  cu: { id: 'uni-11', name: 'Covenant University', shortName: 'CU', location: 'Ota, Ogun State' },
  unijos: { id: 'uni-12', name: 'University of Jos', shortName: 'UNIJOS', location: 'Jos, Plateau State' },
  futa: { id: 'uni-13', name: 'Federal University of Technology, Akure', shortName: 'FUTA', location: 'Akure, Ondo State' },
  buk: { id: 'uni-14', name: 'Bayero University', shortName: 'BUK', location: 'Kano, Kano State' },
  uniuyo: { id: 'uni-15', name: 'University of Uyo', shortName: 'UNIUYO', location: 'Uyo, Akwa Ibom State' },
  biu: { id: 'uni-16', name: 'Benson Idahosa University', shortName: 'BIU', location: 'Benin City, Edo State' },
};


export const mockUsers: Record<string, User> = {
  user_1: {
    id: 'user_1',
    fullName: 'Jane Doe',
    username: 'janedoe',
    email: 'jane@test.com',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-4.0.3&auto=format&fit=crop&w=150&q=80',
    coverPhoto: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    university: mockUniversities.unilag,
    faculty: 'Engineering',
    bio: 'Software Engineering student. Tech enthusiast. Coffee addict ☕️',
    isVerified: true,
    joinedDate: 'Jan 2024',
    reputation: 2450,
    postsCount: 142,
    followersCount: 3800,
    followingCount: 450,
  },
  user_2: {
    id: 'user_2',
    fullName: 'Alex Johnson',
    username: 'alex_j',
    email: 'alex@test.com',
    avatar: 'https://images.unsplash.com/photo-1599566150163-29194dcaad36?ixlib=rb-4.0.3&auto=format&fit=crop&w=150&q=80',
    coverPhoto: 'https://images.unsplash.com/photo-1510784722466-f2aa9c52fff6?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    university: mockUniversities.uniben,
    faculty: 'Business Administration',
    bio: 'Future CEO. Marketing strategies and finance.',
    isVerified: false,
    joinedDate: 'Feb 2024',
    reputation: 1200,
    postsCount: 45,
    followersCount: 890,
    followingCount: 320,
  },
  user_3: {
    id: 'user_3',
    fullName: 'Dr. Sarah Smith',
    username: 'sarah_med',
    email: 'sarah@test.com',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?ixlib=rb-4.0.3&auto=format&fit=crop&w=150&q=80',
    coverPhoto: 'https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    university: mockUniversities.ui,
    faculty: 'Medicine & Surgery',
    bio: 'Medical student aiming for neurology. 🧠 Health tips and study aesthetics.',
    isVerified: true,
    joinedDate: 'Nov 2023',
    reputation: 5600,
    postsCount: 320,
    followersCount: 12400,
    followingCount: 150,
  },
};
